/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomDisplayElement } from './customDisplayElement';
import { Style } from './style';
import { Image } from './image';


export interface Col { 
    id: number;
    width: number;
    colOffset: number;
    displayOrder: number;
    image: Image;
    title: string;
    description: string;
    url: string;
    style: Style;
    leaf: boolean;
    layout?: CustomDisplayElement;
}

