/**
 * title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TextAlign = 'ABOVE' | 'UNDER' | 'LEFT' | 'RIGHT' | 'TOP' | 'BOTTOM' | 'CENTER';

export const TextAlign = {
    Above: 'ABOVE' as TextAlign,
    Under: 'UNDER' as TextAlign,
    Left: 'LEFT' as TextAlign,
    Right: 'RIGHT' as TextAlign,
    Top: 'TOP' as TextAlign,
    Bottom: 'BOTTOM' as TextAlign,
    Center: 'CENTER' as TextAlign
};

